- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - git
      - jq
      - tmux
      - wget
      - zsh
  - name: Install zsh
    shell: wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
  - name: Change default shell
    command: chsh -s /usr/bin/zsh jlo
